services:
  db:
    container_name: musterm-db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=musterm
      - MYSQL_PORT=3307
    ports:
      - 3306:3307
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -P 3306 -u root -p${DB_PASSWORD} "]
      interval: 3s
      timeout: 5s
      retries: 10

  api:
    container_name: musterm-api
    build: .
    command: fastapi run main.py --port 8001
    volumes:
      - .:/app/mustermAPI
    env_file:
      - ./.env.prod
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
